Repository rogov-dvp/medical-imaging-matching, pull requests merged in 2021-12, with the labels that each got.

#195 Changed all tests to a specific naming convention
  src/predicting/ims/tests_main.py
  src/training/models/tests_ORB.py
  src/training/models/tests_SSIM.py
  src/training/models/tests_siamese2.py
  src/training/tests_da_numpy.py
  src/training/tests_da_unit.py
Labels: task

#196 Added a set of 3 unit tests to ORB and SSIM. One unit test checks if …
  src/training/models/ORB.py
  src/training/models/tests_ORB.py
  src/training/models/tests_SSIM.py
Labels: exploration

#197 Preprocess data
  preprocessing/preprocess_data.py
  preprocessing/preprocess_test.py
Labels: task

#198 Preprocess test
  preprocessing/preprocess_data.py
  preprocessing/preprocess_test.py
Labels: chore

#204 progress notes
  docs/gitstats-emily/december.md
Labels: exploration

#202 Add Progress this week
  docs/gitstats-marieke/December.md
Labels: chore

#200 Add Reporting for the Last Week
  docs/gitstats-Niklas/Report.md
Labels: chore

#201 Adding information to gitstats for demeber.md
  docs/.DS_Store
  docs/gitstats-alex/decemer.md
  docs/gitstats-alex/november.md
  src/training/models/tests_ORB.py
  src/training/models/tests_SSIM.py
  test_images_kaggle/.DS_Store
Labels: chore

#203 Data cleaning tests
  preprocessing/data_cleaning.py
  preprocessing/data_cleaning_test.py
Labels: task

#205 Implement testing
  src/training/models/BatchBuilder.py
  src/training/models/CNNTripletModel.py
  src/training/models/tests_BatchBuilder.py
  src/training/models/tests_CNNTripletModel.py
Labels: task

#207 fixed tests_ORB.py and test_SSIM.py unit tests
  src/training/models/tests_ORB.py
  src/training/models/tests_SSIM.py
Labels: exploration
