Repository rogov-dvp/medical-imaging-matching, pull requests merged in 2021-10, with the labels that each got.

#18 added client meeting notes to repo
  docs/client_meeting_notes/Client Meeting Notes - September 22.pdf
  docs/client_meeting_notes/Client Meeting Notes - September 29.pdf
  docs/project_requirements/features.md
  docs/project_requirements/possible_features.md
  docs/project_requirements/tech_stack.md
  docs/project_requirements/testing_plan.md
  docs/project_requirements/user_groups.md
Labels: task

#44 add issue 32 to docs
  docs/gitstats-Niklas/October.md
Labels: exploration, task

#36 Gitstats alex/issue 23
  docs/gitstats-alex/october.md
Labels: chore, task

#39 gitstats-emily/issue 21
  docs/gitstats-emily/october.md
Labels: chore, task

#48 Add Issue 25 to docs
  docs/gitstats-Niklas/October.md
Labels: exploration, task

#52 added team meeting notes to repo
  docs/team_meeting_notes/week3.md
  docs/team_meeting_notes/week4.md
  docs/team_meeting_notes/week5.md
Labels: task

#55 restructure and added base group eval file
  docs/project_requirements/COSC 499 Resaerch on Models.pdf
  docs/project_requirements/requirements_group_feedback/group_evaluations.md
Labels: task

#65 Feedback added for LIMS
  docs/project_requirements/requirements_group_feedback/group_evaluations.md
Labels: exploration, task

#66 Feedback for the AGMeeting Presentations
  docs/project_requirements/requirements_group_feedback/group_evaluations.md
Labels: exploration, task

#70 Added comments for MIM group 0
  docs/project_requirements/requirements_group_feedback/group_evaluations.md
Labels: exploration, task

#87 adding doc with our answers to questions from peers
  docs/project_requirements/requirements_report/peer_questions.md
Labels: chore

#110 Folder for Exploration with notebook exploring triplet loss
  docs/.DS_Store
  docs/exploration/Triplet_Loss_MNIST.ipynb
Labels: exploration
