Repository rogov-dvp/medical-imaging-matching, pull requests merged in 2021-11, with the labels that each got.

#124 week8 team meeting notes
  docs/team_meeting_notes/week8.md
  docs/team_meeting_notes/week9.md
Labels: chore

#126 SSIM code base
  src/models/SSIM.py
Labels: task

#127 Data cleaning
  docs/data_preprocessing/data_cleaning.md
  preprocessing/data_augmentation.py
  preprocessing/data_cleaning.py
  requirements-dev.txt
  requirements_dev.txt
Labels: exploration

#129 unit test framework formatting - skeleton
  preprocessing/da_unit_testing.py
Labels: chore

#130 Code for data cleaning, missing data values.. still needs work
  preprocessing/data_cleaning.py
Labels: task

#132 Created a new folder. It is the folder that organizes, sends, collect…
  src/IMS/main.py
  src/IMS/status_bar.py
  src/IMS/unprocessed_paths.txt
Labels: chore

#135 Siamese exploration and got some working test code
  src/models/siamese.py
  src/models/siamese2.py
Labels: exploration

#134 Initial Testcases to implement for CNNs
  docs/.DS_Store
  docs/Models/CNN_Tests.py
Labels: chore

#131 Experiment to load apply FaceNet with structure and weights downloaded
  docs/Bond1.jpeg
  docs/Bond2.jpg
  docs/Bond3.jpg
  docs/FaceNet_Experiments.py
  docs/project_requirements/features.md
  docs/triplet_loss_function.py
Labels: exploration

#151 documentation on script integrations
  README.md
  docs/script_integration.md
Labels: exploration

#149 Siamese networks Documentation
  docs/Models/siamese_networks.md
  src/models/siamese_unit_testing.py
Labels: exploration

#150 Siamese unit testing implementation
  src/models/siamese2_unit_testing.py
  src/models/siamese_unit_testing.py
Labels: chore

#152 SSIM and ORB code refactored, updated a bit to our case, and commented for clearer understanding
  src/models/ORB.py
  src/models/SSIM.py
Labels: task

#156 Implementation of Triplet Loss for training a CNN
  src/models/CNN_TripletLoss.ipynb
Labels: task

#155 Created unit tests for both SSIM and ORB. Also potential CLI-related code
  src/models/ORB_test.py
  src/models/SSIM.py
  src/models/SSIM_test.py
Labels: chore

#153 Created documentation for SSIM and ORB
  src/models/SSIM.py
Labels: exploration

#158 Documentation for CNN with triplet loss added
  docs/Models/CNN.md
  docs/exploration/CNN.py
  docs/exploration/CNN_Tests.py
Labels: exploration

#159 Siamese implementation
  docs/Models/siamese_networks.md
  src/models/siamese2.py
Labels: task

#160 Added initial tests for CNN
  docs/exploration/Bond1.jpeg
  docs/exploration/Bond2.jpg
  docs/exploration/Bond3.jpg
  docs/exploration/CNN_Tests.py
  docs/exploration/FaceNet_Experiments.py
  docs/exploration/triplet_loss_function.py
Labels: chore

#170 Restructuring file directory
  README.md
  src/models/ORB.py
  src/predicting/ims/main.py
  src/predicting/ims/main_unit_testing.py
  src/predicting/ims/status_bar.py
  src/training/da_unit_testing.py
  src/training/data_augmentation.py
  src/training/models/ORB.py
  src/training/models/SSIM.py
  src/training/models/siamese.py
  src/training/models/siamese2.py
  src/training/models/siamese2_unit_testing.py
Labels: chore

#172 CNN model .py files and adjustments
  src/training/BatchBuilder.py
  src/training/CNNTripletModel.py
  src/training/MainTrainCNN.py
Labels: chore

#173 adjusted data augmentation
  requirements_dev.txt
  src/training/da_numpy.py
  src/training/da_numpy_testing.py
  src/training/data_augmentation.py
  src/training/models/BatchBuilder.py
  src/training/models/CNNTripletModel.py
  src/training/models/CNN_TripletLoss.ipynb
  src/training/models/MainTrainCNN.py
  src/training/models/ORB_test.py
  src/training/models/SSIM_test.py
Labels: chore

#176 Git stats November
  docs/gitstats-marieke/Novemeber.md
Labels: chore

#175 Updated november.md file to do a PR for gitstats
  .DS_Store
  docs/Models/ORB.md
  docs/Models/SSIM.md
  docs/gitstats-alex/november.md
  requirements_dev.txt
  test_images_kaggle/.DS_Store
Labels: chore

#177 gitstats report on my work this week
  docs/gitstats-emily/november.md
Labels: chore

#179 Weekly Activity Report and Images for Peer Testing Added
  docs/gitstats-Niklas/October.md
  docs/gitstats-Niklas/Predict_Structure_Image.png
  docs/gitstats-Niklas/Training_Structure_Image.png
Labels: chore

#180 Added what I did in the word doc/ peer testing #1 report
  docs/gitstats-alex/november.md
Labels: task

#181 Update November.md for report
  docs/gitstats-marieke/Novemeber.md
Labels: task

#183 adding notes on testing that needs to be done
  docs/testing_to_do.md
Labels: task
