Repository rogov-dvp/medical-imaging-matching, pull requests merged in 2022-03, with the labels that each got.

#298 Upload team meeting notes
  docs/team_meeting_notes/term2/March2.md
Labels: chore

#302 Add documentation on this weeks work
  docs/gitstats-Niklas/Report.md
Labels: chore

#312 Updated gitstats for peer testing activities
  docs/gitstats-marieke/March.md
Labels: task

#309 Updating gitstats documents. Prototype video #2 slides
  docs/gitstats-alex/march.md
Labels: task

#310 Updated gitstats for recording
  docs/gitstats-alex/march.md
Labels: exploration

#303 Add graphics from presentation to git
  docs/gitstats-Niklas/Report.md
Labels: task

#313 work done in march
  docs/gitstats-emily/march.md
Labels: chore

#314 documentation on preprocessing for pt2 done
  docs/project_requirements/preprocessing.md
Labels: task

#305 Add 2 papers on one shot learning and medical image analysis
  docs/gitstats-Niklas/Research_Notes.md
Labels: exploration

#316 added notes for this week
  docs/team_meeting_notes/term2/March9.md
Labels: task

#320 Gitstats march update
  docs/gitstats-alex/march.md
Labels: task

#332 Updated March git stats to include peer reviews
  docs/gitstats-marieke/March.md
Labels: task

#333 Updated Gitstats to include work on report
  docs/gitstats-marieke/March.md
Labels: chore

#329 documentation for preprocessing added
  docs/project_requirements/preprocessing.md
Labels: task

#331 added emily notes for gitstats
  docs/gitstats-emily/march.md
Labels: exploration

#324 add progress of this week to gitstats report
  docs/gitstats-Niklas/Report.md
Labels: exploration

#323 Add comments to the gitstats documentation
  docs/gitstats-Niklas/Report.md
Labels: task

#335 Upload Team Meeting Notes
  docs/team_meeting_notes/term2/March16.md
Labels: task

#339 Finally cleared the big training issue
  docs/gitstats-Niklas/Report.md
Labels: task

#338 Document progress
  docs/gitstats-Niklas/Report.md
Labels: chore

#342 work so far:
  docs/gitstats-emily/march.md
Labels: task

#344 update git stats
  docs/gitstats-marieke/March.md
Labels: exploration

#345 Research into online hard-negative mining
  docs/exploration/embedding_issues.md
Labels: exploration

#351 Integration Notes
  docs/gitstats-emily/march.md
  docs/integration/script_integration.md
Labels: task

#350 Unit tests for breast detection and some minor changes to breast_detection script
  preprocessing/breast_detection/crop_main_file.py
  preprocessing/breast_detection/test_crop_main.py
Labels: chore

#356 update
  docs/gitstats-marieke/March.md
Labels: exploration

#355 added tests for main/integration
  .DS_Store
  docs/.DS_Store
  preprocessing/preprocess_data.py
  src/predicting/ims/main.py
  src/predicting/ims/tests_main.py
  test_images_kaggle/.DS_Store
  test_images_kaggle/processed_images/lmlo/2016_BC003122_ MLO_L.npy
  test_images_kaggle/processed_images/rcc/2016_BC003122_ CC_R.npy
  test_images_kaggle/processed_images/rmlo/2016_BC003122_ MLO_R.npy
Labels: chore

#353 Weekly report
  docs/gitstats-Niklas/Report.md
Labels: task
