Repository rogov-dvp/medical-imaging-matching, pull requests merged in 2022-02, with the labels that each got.

#259 team notes February 2
  docs/team_meeting_notes/term2/February2.md
Labels: chore

#260 Preprocessing cnn connection
  docs/data_preprocessing/image_cropping.md
  preprocessing/preprocess_data.py
  src/predicting/ims/main.py
  src/training/models/MainRead.py
  src/training/models/main_read_kaggle.py
  src/training/models/main_train_cnn_kaggle.py
  src/training/models/main_train_kaggle.py
  src/training/models/read_preprocessed.py
  test_images_kaggle/processed_images/lcc/2016_BC003122_ CC_L.npy
Labels: task

#261 Testing Preprocessing and CNN connection
  requirements_dev.txt
  src/training/models/BatchBuilder.py
  src/training/models/main_train_cnn_kaggle.py
  src/training/models/main_train_kaggle.py
  src/training/models/test_integration_read_kaggle.py
Labels: chore

#262 description of current issues added
  docs/integration/preprocessing_cnn_integration.md
Labels: exploration

#263 Added detail to the NumPy exploration file
  docs/exploration/CNN_on_Remote/BatchBuilder.py
  docs/exploration/NumPy_limitations.md
Labels: exploration

#264 Created february file for gistats
  docs/gitstats-alex/february.md
Labels: task

#266 Document Progress on Gradient Explosion Progress
  docs/gitstats-Niklas/Report.md
Labels: exploration

#274 Upload team meeting notes
  docs/team_meeting_notes/term2/Februrary9.md
Labels: chore

#275 Updated Feb gitstats
  docs/gitstats-marieke/February.md
Labels: exploration

#276 Research on Triplet Loss Encoding/Embedding
  docs/exploration/embedding_issues.md
  docs/gitstats-emily/february.md
Labels: exploration

#277 Batch builder updated implementation
  docs/exploration/BatchBuilder.md
  docs/exploration/CNN_on_Remote/BatchBuilder.py
  src/training/models/tests_BatchBuilder.py
Labels: task

#281 Add Keras example
  docs/exploration/CNN_on_Remote/siamesenetwork.ipynb
Labels: exploration

#280 add notebook to adjust on gpu server
  docs/exploration/Siamese.ipynb
  docs/exploration/Siamese_similarity.ipynb
  docs/exploration/siamesenetwork.ipynb
Labels: exploration

#278 Task/iss 267v2
  docs/gitstats-alex/february.md
  preprocessing/breast_detection/crop_img_script.py
  preprocessing/breast_detection/img_data/2016_BC003122_ CC_L.jpg
  preprocessing/breast_detection/img_data/2016_BC003122_ CC_L.xml
  preprocessing/breast_detection/img_data/2016_BC003122_ CC_R.jpg
  preprocessing/breast_detection/img_data/2016_BC003122_ CC_R.xml
  preprocessing/breast_detection/img_data/2016_BC003122_ MLO_L.jpg
  preprocessing/breast_detection/img_data/2016_BC003122_ MLO_L.xml
  preprocessing/breast_detection/img_data_cropped/2016_BC003122_ CC_L.jpg
  preprocessing/breast_detection/img_data_cropped/2016_BC003122_ CC_R.jpg
  preprocessing/breast_detection/img_data_cropped/2016_BC003122_ MLO_L.jpg
  preprocessing/detecting_breast/contour.png
  preprocessing/detecting_breast/crop_image.py
  preprocessing/detecting_breast/crop_mamm.py
  preprocessing/detecting_breast/det_br.py
Labels: task

#288 upload team meeting notes
  docs/team_meeting_notes/term2/Februrary16.md
Labels: task

#294 Work done this week added to Feb md
  docs/gitstats-marieke/February.md
Labels: exploration

#293 summary of work done this week
  docs/gitstats-emily/february.md
Labels: task

#296 This week's progress. I will continue working on this during the week
  docs/gitstats-alex/february.md
Labels: exploration
