Repository rogov-dvp/medical-imaging-matching, pull requests merged in 2022-01, with the labels that each got.

#222 adding team notes
  docs/team_meeting_notes/term2/January19.md
Labels: chore

#225 updates to doc on siamese networks
  docs/Models/siamese_networks.md
Labels: chore

#223 Made updates to ORB and SSIM documents of models
  docs/Models/ORB.md
  docs/Models/SSIM.md
Labels: chore

#227 research into image cropping
  docs/data_preprocessing/image_cropping.md
  preprocessing/preprocess_data.py
Labels: exploration

#228 Completed regression testing for models. Additionally, created a docu…
  docs/testing_instructions/regression_testing.md
  src/training/models/ORB.py
  src/training/models/_regtest_outputs/tests_reg_ORB.test_dummy_data_different.out
  src/training/models/_regtest_outputs/tests_reg_ORB.test_dummy_data_identical.out
  src/training/models/_regtest_outputs/tests_reg_ORB.test_dummy_data_similar.out
  src/training/models/_regtest_outputs/tests_reg_ORB.test_general.out
  src/training/models/_regtest_outputs/tests_reg_ORB.test_img1_not_none.out
  src/training/models/_regtest_outputs/tests_reg_ORB.test_img2_not_none.out
  src/training/models/tests_reg_ORB.py
  src/training/models/tests_reg_SSIM.py
  src/training/models/tests_reg_all_models.py
Labels: task

#226 Add Gantt Chart for Term 2
  docs/project_requirements/Gantt Chart/Gantt_Chart.pages
  docs/project_requirements/Gantt Chart/Gantt_Chart.png
Labels: chore

#229 Add Justification and further details to the models CNN documentation
  docs/Models/CNN.md
Labels: chore

#232 Exploration into the batch builder
  docs/exploration/BatchBuilder.md
  docs/exploration/CNN_on_Remote/BatchBuilder.py
Labels: exploration

#231 Exploration on cropping breast in mammograms
  preprocessing/detecting_breast/contour.png
  preprocessing/detecting_breast/crop_image.py
  preprocessing/detecting_breast/crop_mamm.py
  preprocessing/detecting_breast/det_br.py
Labels: exploration

#233 proposals on how to connect preprocessing and cnn
  docs/integration/integration_testing.md
  docs/integration/preprocessing_cnn_integration.md
  docs/integration/script_integration.md
Labels: task

#243 Added notes for this week
  docs/team_meeting_notes/term2/January26.md
Labels: chore

#244 More in-depth testing to CNN
  docs/exploration/CNN.py
  docs/exploration/CNN_Tests.py
  src/training/models/CNNTripletModel.py
  src/training/models/tests_CNNTripletModel.py
Labels: task

#246 Remote preprocessing
  data/mismatches_remote.csv
  preprocessing/preprocess_data_remote.py
Labels: task

#247 NumPy files exploration
  docs/exploration/CNN_on_Remote/BatchBuilder.py
  docs/exploration/NumPy_limitations.md
Labels: exploration

#248 task/iss-235 - update on the task. Still needs work but it's close. I…
  docs/gitstats-alex/january.md
Labels: task

#251 Preprocessed cnn connection
  data/mismatches.csv
  preprocessing/preprocess_data.py
  preprocessing/preprocess_imgs.py
  src/predicting/ims/main.py
  src/training/models/MainRead.py
  src/training/models/read_preprocessed.py
  test_images_kaggle/processed_images/lcc/2016_BC003122_ CC_L.npy
  test_images_kaggle/processed_images/lcc/2016_BC014002_ CC_L.npy
  test_images_kaggle/processed_images/lcc/2016_BC016802_ CC_L.npy
  test_images_kaggle/processed_images/lcc/2016_BC016983_ CC_L.npy
  test_images_kaggle/processed_images/lcc/2017_BC006222_ CC_L.npy
  test_images_kaggle/processed_images/lcc/2017_BC011081_ CC_L.npy
  test_images_kaggle/processed_images/lcc/2017_BC015902_ CC_L.npy
  test_images_kaggle/processed_images/lcc/2017_BC017441_ CC_L.npy
  test_images_kaggle/processed_images/lcc/2017_BC019521_ CC_L.npy
  test_images_kaggle/processed_images/lcc/2017_BC019621_ CC_L.npy
  test_images_kaggle/processed_images/lcc/2017_BC019681_ CC_L.npy
  test_images_kaggle/processed_images/lcc/2017_BC019782_ CC_L.npy
  test_images_kaggle/processed_images/lcc/2017_BC019861_ CC_L.npy
  test_images_kaggle/processed_images/lmlo/2016_BC003122_ MLO_L.npy
  test_images_kaggle/processed_images/lmlo/2016_BC014002_ MLO_L.npy
  test_images_kaggle/processed_images/lmlo/2016_BC016802_ MLO_L.npy
  test_images_kaggle/processed_images/lmlo/2016_BC016983_ MLO_L.npy
  test_images_kaggle/processed_images/lmlo/2017_BC006222_ MLO_L.npy
  test_images_kaggle/processed_images/lmlo/2017_BC011081_ MLO_L.npy
  test_images_kaggle/processed_images/lmlo/2017_BC015902_ MLO_L.npy
  test_images_kaggle/processed_images/lmlo/2017_BC017441_ MLO_L.npy
  test_images_kaggle/processed_images/lmlo/2017_BC019521_ MLO_L.npy
  test_images_kaggle/processed_images/lmlo/2017_BC019621_ MLO_L.npy
  test_images_kaggle/processed_images/lmlo/2017_BC019681_ MLO_L.npy
  test_images_kaggle/processed_images/lmlo/2017_BC019782_ MLO_L.npy
  test_images_kaggle/processed_images/lmlo/2017_BC019861_ MLO_L.npy
  test_images_kaggle/processed_images/rcc/2016_BC003122_ CC_R.npy
  test_images_kaggle/processed_images/rcc/2016_BC016802_ CC_R.npy
  test_images_kaggle/processed_images/rcc/2016_BC016983_ CC_R.npy
  test_images_kaggle/processed_images/rcc/2017_BC006222_ CC_R.npy
  test_images_kaggle/processed_images/rcc/2017_BC011081_ CC_R.npy
  test_images_kaggle/processed_images/rcc/2017_BC015902_ CC_R.npy
  test_images_kaggle/processed_images/rcc/2017_BC017441_ CC_R.npy
  test_images_kaggle/processed_images/rcc/2017_BC019521_ CC_R.npy
  test_images_kaggle/processed_images/rcc/2017_BC019621_ CC_R.npy
  test_images_kaggle/processed_images/rcc/2017_BC019681_ CC_R.npy
  test_images_kaggle/processed_images/rcc/2017_BC019782_ CC_R.npy
  test_images_kaggle/processed_images/rcc/2017_BC019861_ CC_R.npy
  test_images_kaggle/processed_images/rmlo/2016_BC003122_ MLO_R.npy
  test_images_kaggle/processed_images/rmlo/2016_BC016802_ MLO_R.npy
  test_images_kaggle/processed_images/rmlo/2016_BC016983_ MLO_R.npy
  test_images_kaggle/processed_images/rmlo/2017_BC006222_ MLO_R.npy
  test_images_kaggle/processed_images/rmlo/2017_BC011081_ MLO_R.npy
  test_images_kaggle/processed_images/rmlo/2017_BC015902_ MLO_R.npy
  test_images_kaggle/processed_images/rmlo/2017_BC017441_ MLO_R.npy
  test_images_kaggle/processed_images/rmlo/2017_BC019521_ MLO_R.npy
  test_images_kaggle/processed_images/rmlo/2017_BC019621_ MLO_R.npy
  test_images_kaggle/processed_images/rmlo/2017_BC019681_ MLO_R.npy
  test_images_kaggle/processed_images/rmlo/2017_BC019782_ MLO_R.npy
  test_images_kaggle/processed_images/rmlo/2017_BC019861_ MLO_R.npy
Labels: exploration
